name: Flask App Boot Test

on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  test-flask-startup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up .env file
        run: |
          cp .env.example .env
          sed -i 's/^APIKEY=.*/APIKEY=${{ secrets.APIKEY }}/' .env

      - name: Test Flask startup
        run: |
          source venv/bin/activate
          export FLASK_APP=recordapp.py
          export FLASK_ENV=development
          flask run --no-debugger --no-reload &
          sleep 5
          if pgrep -f "flask run" > /dev/null
          then
            echo "✅ Flask app started successfully."
          else
            echo "❌ Flask app failed to start."
            exit 1
          fi
