name: Flask App Boot Test

on:
  push:
    branches:
      - '**'  # Runs on push to any branch

jobs:
  test-flask-startup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install pytest and pytest-cov for test coverage

      - name: Set up .env file
        run: |
          cp .env.example .env
          sed -i 's|^API_KEY=.*|API_KEY=${{ secrets.APIKEY }}|' .env
          cat .env

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          export FLASK_APP=recordapp.py
          export FLASK_ENV=development
          pytest --maxfail=1 --disable-warnings -q --cov=recordapp --cov-report=xml test  # Look inside 'test' folder

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  # Upload the coverage report generated in the previous step

      - name: Test Flask startup
        run: |
          source venv/bin/activate
          export FLASK_APP=recordapp.py
          export FLASK_ENV=development
          flask run --no-debugger --no-reload &
          sleep 5
          if pgrep -f "flask run" > /dev/null
          then
            echo "✅ Flask app started successfully."
          else
            echo "❌ Flask app failed to start."
            exit 1
          fi
